name: Detekt

on:
  workflow_dispatch:
  pull_request: { }

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  CI_GRADLE_ARG_PROPERTIES: --stacktrace

jobs:
  linting:
    name: Run Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Java
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Run Detekt
        run: ./gradlew detektAll

      - name: Upload report
        uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
