name: Detekt

on:
  workflow_dispatch:
  pull_request: { }

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  CI_GRADLE_ARG_PROPERTIES: --stacktrace

jobs:
  linting:
    name: Run Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Java
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Run Detekt
        run: ./gradlew detektAll

      - name: Upload report
        uses: github/codeql-action/upload-sarif@458d36d7d4f47d0dd16ca424c1d3cda0060f1360 # v3.35.5
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
